[2023-04-01T17:35:07.818+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_status_update.tweetText manual__2023-04-01T17:35:05.694440+00:00 [queued]>
[2023-04-01T17:35:07.826+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_status_update.tweetText manual__2023-04-01T17:35:05.694440+00:00 [queued]>
[2023-04-01T17:35:07.827+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-01T17:35:07.828+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-04-01T17:35:07.829+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-01T17:35:07.837+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): tweetText> on 2023-04-01 17:35:05.694440+00:00
[2023-04-01T17:35:07.843+0000] {standard_task_runner.py:55} INFO - Started process 6949 to run task
[2023-04-01T17:35:07.846+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_status_update', 'tweetText', 'manual__2023-04-01T17:35:05.694440+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/twitterStatusUpdatePipeline.py', '--cfg-path', '/tmp/tmp4kts5__m']
[2023-04-01T17:35:07.847+0000] {standard_task_runner.py:83} INFO - Job 173: Subtask tweetText
[2023-04-01T17:35:07.896+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_status_update.tweetText manual__2023-04-01T17:35:05.694440+00:00 [running]> on host 16ecf75c2681
[2023-04-01T17:35:07.953+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_status_update
AIRFLOW_CTX_TASK_ID=tweetText
AIRFLOW_CTX_EXECUTION_DATE=2023-04-01T17:35:05.694440+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-01T17:35:05.694440+00:00
[2023-04-01T17:35:07.955+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/twitterStatusUpdatePipeline.py", line 27, in tweetText
    is_posted = ins.tweet_text(content)
TypeError: tweet_text() takes 1 positional argument but 2 were given
[2023-04-01T17:35:07.964+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_status_update, task_id=tweetText, execution_date=20230401T173505, start_date=20230401T173507, end_date=20230401T173507
[2023-04-01T17:35:07.972+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 173 for task tweetText (tweet_text() takes 1 positional argument but 2 were given; 6949)
[2023-04-01T17:35:08.020+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-01T17:35:08.033+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
