[2023-04-01T02:49:39.083+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_status_update.updateStatus scheduled__2023-03-31T21:00:00+00:00 [queued]>
[2023-04-01T02:49:39.091+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_status_update.updateStatus scheduled__2023-03-31T21:00:00+00:00 [queued]>
[2023-04-01T02:49:39.092+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-01T02:49:39.094+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 3
[2023-04-01T02:49:39.095+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-01T02:49:39.105+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): updateStatus> on 2023-03-31 21:00:00+00:00
[2023-04-01T02:49:39.112+0000] {standard_task_runner.py:55} INFO - Started process 399 to run task
[2023-04-01T02:49:39.116+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_status_update', 'updateStatus', 'scheduled__2023-03-31T21:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/twitterStatusUpdatePipeline.py', '--cfg-path', '/tmp/tmp63xx1erk']
[2023-04-01T02:49:39.117+0000] {standard_task_runner.py:83} INFO - Job 64: Subtask updateStatus
[2023-04-01T02:49:39.174+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_status_update.updateStatus scheduled__2023-03-31T21:00:00+00:00 [running]> on host 6e1a3323bcdd
[2023-04-01T02:49:39.233+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_status_update
AIRFLOW_CTX_TASK_ID=updateStatus
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T21:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-31T21:00:00+00:00
[2023-04-01T02:49:41.526+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/twitterStatusUpdatePipeline.py", line 24, in updateStatus
    from utils.twitterStatusUpdate import TwitterStatusUpdate
  File "/opt/airflow/dags/utils/twitterStatusUpdate.py", line 31, in <module>
    ins.updateStatus()
  File "/opt/airflow/dags/utils/twitterStatusUpdate.py", line 27, in updateStatus
    api.update_status("We're like Tinder, but with more hodling and less swiping.")
  File "/home/airflow/.local/lib/python3.7/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/tweepy/api.py", line 1149, in update_status
    ), status=status, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/tweepy/api.py", line 265, in request
    raise Forbidden(resp)
tweepy.errors.Forbidden: 403 Forbidden
187 - Status is a duplicate.
[2023-04-01T02:49:41.556+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=twitter_status_update, task_id=updateStatus, execution_date=20230331T210000, start_date=20230401T024939, end_date=20230401T024941
[2023-04-01T02:49:41.575+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 64 for task updateStatus (403 Forbidden
187 - Status is a duplicate.; 399)
[2023-04-01T02:49:41.604+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-01T02:49:41.625+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
