[2023-04-01T12:45:07.372+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_status_with_image_update.get_folder_images manual__2023-04-01T12:45:04.848473+00:00 [queued]>
[2023-04-01T12:45:07.390+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_status_with_image_update.get_folder_images manual__2023-04-01T12:45:04.848473+00:00 [queued]>
[2023-04-01T12:45:07.391+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-01T12:45:07.392+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-04-01T12:45:07.393+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-01T12:45:07.411+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): get_folder_images> on 2023-04-01 12:45:04.848473+00:00
[2023-04-01T12:45:07.419+0000] {standard_task_runner.py:55} INFO - Started process 10165 to run task
[2023-04-01T12:45:07.426+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_status_with_image_update', 'get_folder_images', 'manual__2023-04-01T12:45:04.848473+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/twitterImageWithTextUpdatePipeline.py', '--cfg-path', '/tmp/tmpl43q9tv0']
[2023-04-01T12:45:07.428+0000] {standard_task_runner.py:83} INFO - Job 91: Subtask get_folder_images
[2023-04-01T12:45:07.513+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_status_with_image_update.get_folder_images manual__2023-04-01T12:45:04.848473+00:00 [running]> on host 21dcead862af
[2023-04-01T12:45:07.620+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_status_with_image_update
AIRFLOW_CTX_TASK_ID=get_folder_images
AIRFLOW_CTX_EXECUTION_DATE=2023-04-01T12:45:04.848473+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-01T12:45:04.848473+00:00
[2023-04-01T12:45:07.641+0000] {_default.py:649} WARNING - No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
[2023-04-01T12:45:07.642+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/twitterImageWithTextUpdatePipeline.py", line 34, in get_folder_images
    image_names = image_client.get_file_names(folder_path)
  File "/opt/airflow/dags/utils/get_bq_image.py", line 37, in get_file_names
    client = storage.Client()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 171, in __init__
    _http=_http,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 320, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 272, in __init__
    "Project was not passed and could not be "
OSError: Project was not passed and could not be determined from the environment.
[2023-04-01T12:45:07.659+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_status_with_image_update, task_id=get_folder_images, execution_date=20230401T124504, start_date=20230401T124507, end_date=20230401T124507
[2023-04-01T12:45:07.676+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 91 for task get_folder_images (Project was not passed and could not be determined from the environment.; 10165)
[2023-04-01T12:45:07.716+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-01T12:45:07.731+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
